version: '3'
services:
  database:
    image: 'postgres:latest'
    ports:
      - "9944:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: localdb
  ecc:
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - database
